name: C Assignment Grading

on: [push]

jobs:
  grade-assignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Grade the submission
        run: |
          echo "::group::채점 시작"

          # =========================================================
          # 1. 실행 결과 확인
          # =========================================================
          echo "1. 실행 결과 확인 중..."
          # GCC로 컴파일
          gcc main.c -o myprogram
          if [ $? -ne 0 ]; then
            echo "::error::컴파일 실패. 코드를 확인해주세요."
            exit 1
          fi

          # 프로그램 실행 결과를 output.txt에 저장
          ./myprogram > output.txt
          
          # output.txt와 정답 파일(correct_output.txt) 비교
          if diff -q output.txt correct_output.txt >/dev/null; then
            echo "::notice::✔ 실행 결과가 정답과 일치합니다."
          else
            echo "::error::실행 결과가 정답과 다릅니다. output.txt 파일을 확인하세요."
            exit 1
          fi

          # =========================================================
          # 2. 주석 개수 확인
          # =========================================================
          echo "2. 주석 개수 확인 중..."
          # "//" 형태의 주석과 "/* */" 형태의 주석을 모두 카운트
          COMMENT_COUNT=$(grep -E '^\s*(//|/\*).*$' main.c | wc -l)
          echo "발견된 주석 줄 수: $COMMENT_COUNT 줄"
          
          if [ $COMMENT_COUNT -ge 3 ]; then
            echo "::notice::✔ 주석이 3줄 이상 존재합니다."
          else
            echo "::error::주석이 3줄 미만입니다. 최소 3줄의 주석을 작성해야 합니다."
            exit 1
          fi

          echo "::notice::✔ 모든 테스트를 통과했습니다. PASS!"
          echo "::endgroup::"
          
